name = "Day4"
version = "0.1.0"
license = "license"
author = "Roman Wallner- Silberhuber"
maintainer = "21206536+romanWSgit@users.noreply.github.com"
copyright = "Copyright 2022, Roman Wallner- Silberhuber"

[dependencies]
stdlib.git = "https://github.com/fortran-lang/stdlib"
stdlib.branch = "stdlib-fpm"
M_strings = { git = "https://github.com/urbanjost/M_strings.git" ,tag="v1.0.1"}

[build]
auto-executables = true
auto-tests = true
auto-examples = true
[install]
library = false
